export const GET_INIT_CONTENT = 'Home/GET_INIT_CONTENT'
export const CHANGE_SIGNIN_STATUS = 'Home/CHANGE_SIGNIN_STATUS'
export const ADD_SIGNIN_GOLD = 'Home/ADD_SIGNIN_GOLD'
export const ADD_PERFECT_GOLD = 'Home/ADD_PERFECT_GOLD'